import { Plus, Search, Settings2, SlidersHorizontal } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { DiveLog, RecreationalGas } from '../../modules/dives/domain/dive.model';
import { getAllDives } from '../../storage/repositories/diveRepository';
import { Badge } from '../components/common/Badge';
import { RatingStars } from '../components/common/RatingStars';

const date = (value: string) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value));
export function LogbookView({ onDive, onNewDive, onPresets }: { onDive: (dive: DiveLog) => void; onNewDive: () => void; onPresets: () => void }) {
  const [dives, setDives] = useState<DiveLog[]>([]); const [query, setQuery] = useState(''); const [gas, setGas] = useState('all'); const [type, setType] = useState('all');
  useEffect(() => { void getAllDives().then(setDives); }, []);
  const types = [...new Set(dives.map((dive) => dive.diveType))];
  const filtered = useMemo(() => dives.filter((dive) => `${dive.siteName} ${dive.location}`.toLowerCase().includes(query.toLowerCase()) && (gas === 'all' || dive.gasMix === gas) && (type === 'all' || dive.diveType === type)), [dives, gas, query, type]);
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">LOGBOOK / ALL DIVES</span><h1>Every descent, remembered.</h1><p className="muted">{filtered.length} of {dives.length} recorded dives</p></div><div className="logbook-actions"><button className="button button-secondary mobile-presets-button" onClick={onPresets}><Settings2 size={15} /> Gear Presets</button><button className="button button-primary" onClick={onNewDive}><Plus size={17} /> Log New Dive</button></div></section><section className="filters"><label className="search-field"><Search size={17} /><input placeholder="Search site or location" value={query} onChange={(event) => setQuery(event.target.value)} /></label><span className="filter-label"><SlidersHorizontal size={15} /> Filters</span><select value={gas} onChange={(event) => setGas(event.target.value)}><option value="all">All gas mixes</option>{(['AIR', 'EAN32', 'EAN36'] as RecreationalGas[]).map((item) => <option key={item}>{item}</option>)}</select><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All dive types</option>{types.map((item) => <option key={item}>{item}</option>)}</select></section><section className="table-wrap"><div className="table-header"><span>DIVE</span><span>DATE / LOCATION</span><span>DEPTH</span><span>DURATION</span><span>GAS</span><span>RATING</span></div>{filtered.map((dive) => <button className="table-row" key={dive.id} onClick={() => onDive(dive)}><strong>#{dive.diveNumber.toString().padStart(3, '0')}</strong><span><b>{date(dive.date)}</b><small>{dive.siteName}, {dive.location}</small></span><strong>{dive.maxDepthMeters.toFixed(1)} m</strong><span>{Math.round(dive.duration / 60)} min</span><Badge>{dive.gasMix}</Badge><RatingStars value={dive.rating} /></button>)}{filtered.length === 0 && <div className="empty-state">No dives match those filters.</div>}</section></div>;
}